/**
 * Post-build: writes dist/<route>/index.html with per-page SEO in <head>.
 * Run via: npm run build (vite closeBundle) or npm run prerender
 */
import {
  existsSync,
  mkdirSync,
  readFileSync,
  writeFileSync,
} from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import {
  injectSeo,
  listPrerenderRoutes,
  loadSeoConfig,
  resolveSeoForPath,
} from "./seo-html.mjs";

const root = dirname(fileURLToPath(import.meta.url));
const distDir = join(root, "..", "dist");
const DEBUG = process.env.PRERENDER_DEBUG === "1";

export function runPrerender({ dist = distDir } = {}) {
  const indexPath = join(dist, "index.html");

  if (!existsSync(indexPath)) {
    throw new Error(
      "[prerender] dist/index.html not found. Run vite build first.",
    );
  }

  const seo = loadSeoConfig();
  const baseHtml = readFileSync(indexPath, "utf8");
  const routes = listPrerenderRoutes();
  const written = [];

  for (const routePath of routes) {
    const { path, config, matched, usedFallback } = resolveSeoForPath(
      routePath,
      { logRoute: DEBUG },
    );

    if (usedFallback && routePath !== "/") {
      console.warn(
        `[prerender] WARNING: no SEO entry for ${routePath}, using default homepage metadata`,
      );
    }

    const html = injectSeo(baseHtml, config);
    const segments =
      routePath === "/" ? [] : routePath.replace(/^\//, "").split("/");
    const outDir = join(dist, ...segments);
    const outFile =
      routePath === "/" ? indexPath : join(outDir, "index.html");

    mkdirSync(outDir, { recursive: true });
    writeFileSync(outFile, html, "utf8");

    written.push({
      routePath: path,
      outFile: outFile.replace(/\\/g, "/"),
      title: config.title,
      matched,
    });

    if (DEBUG) {
      console.log(`[prerender] wrote ${outFile} <- ${matched}`);
    }
  }

  writeRedirectsFile(dist, routes);
  writePrerenderManifest(dist, written, seo);

  console.log("");
  console.log("  ┌─ SEO prerender complete ─────────────────────────────");
  console.log(`  │  Pages written: ${written.length}`);
  console.log(`  │  Manifest:      dist/prerender-manifest.json`);
  console.log(`  │  Redirects:     dist/_redirects`);
  console.log("  └──────────────────────────────────────────────────");
  console.log("");

  return written;
}

function writeRedirectsFile(dist, routes) {
  const lines = [
    "# Auto-generated by scripts/prerender-html.mjs — serve prerendered HTML per route",
    "",
  ];

  for (const routePath of routes) {
    if (routePath === "/") continue;
    const target =
      routePath.endsWith("/") ? `${routePath}index.html` : `${routePath}/index.html`;
    lines.push(`${routePath}    ${target}    200`);
  }

  lines.push("", "# SPA fallback for unknown routes only", "/*    /index.html   200", "");

  writeFileSync(join(dist, "_redirects"), lines.join("\n"), "utf8");
}

function writePrerenderManifest(dist, written, seo) {
  const manifest = {
    generatedAt: new Date().toISOString(),
    routeCount: written.length,
    routes: written.map(({ routePath, outFile, title, matched }) => ({
      routePath,
      outFile,
      title,
      matched,
    })),
    seoSource: "src/data/pageSeo.json",
    staticRouteKeys: Object.keys(seo.routes),
    solutionSlugs: Object.keys(seo.solutions),
  };
  writeFileSync(
    join(dist, "prerender-manifest.json"),
    `${JSON.stringify(manifest, null, 2)}\n`,
    "utf8",
  );
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  runPrerender();
}
